from setuptools import setup, find_packages

setup(
    name='neural_decoder',
    version='0.0.1',
    packages=find_packages(include=['neuralDecoder']),
    install_requires=[
        'tensorflow',
        'hydra-core',
        'hydra-submitit-launcher',
        'hydra-optuna-sweeper',
        'transformers',
        'redis',
        'seaborn',
        'pandas',
        'jupyterlab',
        'ipywidgets',
        'tqdm',
        'g2p_en',
        'numpy',
        'scipy',
        'torch',
        'accelerate',
        'bitsandbytes',
        'edit_distance',
        'wandb',
        'hiplot',
        'numba',
        'scikit-learn'
    ]
)
