"""Generate Bab II figures (matplotlib). Reuses helpers from make_figures.py.

Run:  python docs/thesis/figures/make_bab2_figures.py
Outputs: fig_dataset.png, fig_ecog_pipeline.png, fig_transformer_variants.png

Does NOT touch the Bab III figures (those are generated by make_figures.py and
have already been tidied by the user).
"""
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

from make_figures import (
    box, bh, arrow, finish, vstack,
    BLUE_F, BLUE_E, YEL_F, YEL_E, RED_F, RED_E, GRN_F, GRN_E, GRY_F, GRY_E,
    MAIN, SUB, TITLE, SMALL, LINE_H,
)

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Gambar II.1 — Tata letak susunan elektroda (area 6v dipakai, area 44 tidak)
# ---------------------------------------------------------------------------
def fig_dataset():
    fig, ax = plt.subplots(figsize=(7.6, 6.4))

    def grid(ax, cx, cy, used):
        """8x8 mini-grid representing a 64-electrode quadrant."""
        fc = BLUE_E if used else "#c8ccd0"
        n, cell, gap = 8, 0.16, 0.02
        span = n * cell + (n - 1) * gap
        x0 = cx - span / 2
        y0 = cy - span / 2
        for i in range(n):
            for j in range(n):
                x = x0 + j * (cell + gap)
                y = y0 + i * (cell + gap)
                ax.add_patch(plt.Rectangle((x, y), cell, cell, facecolor=fc,
                                           edgecolor="white", linewidth=0.4, zorder=3))

    # Area 44 (left, not used) and Area 6v (right, used) — each = superior + inferior
    # Big background panels
    box(ax, -2.2, 3.0, 3.4, 3.7, "", fc="#f1f3f4", ec=GRY_E)
    box(ax, 2.2, 3.0, 3.4, 3.7, "", fc=BLUE_F, ec=BLUE_E)

    ax.text(-2.2, 4.55, "Area 44\n(tidak dipakai)", ha="center", va="center",
            fontsize=MAIN, color=GRY_E)
    ax.text(2.2, 4.55, "Area 6v\n(dipakai, 128 kanal)", ha="center", va="center",
            fontsize=MAIN, color=BLUE_E, fontweight="bold")

    for cx, used in [(-2.2, False), (2.2, True)]:
        grid(ax, cx, 3.45, used)   # superior
        grid(ax, cx, 1.95, used)   # inferior
    ax.text(-3.95, 3.45, "Sup.", ha="center", va="center", fontsize=SMALL, color=GRY_E, rotation=90)
    ax.text(-3.95, 1.95, "Inf.", ha="center", va="center", fontsize=SMALL, color=GRY_E, rotation=90)

    # arrows down to feature vector
    arrow(ax, (2.2, 1.0), (2.2, 0.2), ec=BLUE_E, lw=1.8)
    box(ax, 2.2, -0.45, 5.4, 1.1,
        "Vektor fitur 256-dim per bin 20 ms\n@i@128 threshold crossings + 128 spike band power",
        fc=GRN_F, ec=GRN_E, fs=SUB)

    finish(fig, ax, "fig_dataset.png", (-4.4, 5.2), (-1.1, 5.2))


# ---------------------------------------------------------------------------
# Gambar II.2 — Alur dekode sinyal ECoG menjadi teks (umum)
# ---------------------------------------------------------------------------
def fig_ecog_pipeline():
    fig, ax = plt.subplots(figsize=(5.2, 9.0))
    W, x = 5.2, 0
    steps = [
        ("Sinyal ECoG mentah", GRY_F, GRY_E),
        ("Praproses & ekstraksi fitur\n@i@matriks fitur  T x 256", BLUE_F, BLUE_E),
        ("Dekoder fonem (CTC)\n@i@RNN / model Transformer", YEL_F, YEL_E),
        ("Probabilitas fonem  T x 41", YEL_F, YEL_E),
        ("Model bahasa\n@i@5-gram WFST + rescoring neural", BLUE_F, BLUE_E),
        ("Teks akhir", GRN_F, GRN_E),
    ]
    ys = vstack(ax, x, steps, w=W, gap=1.15)
    last_y, last_h = ys[-1]
    finish(fig, ax, "fig_ecog_pipeline.png",
           (-W / 2 - 0.3, W / 2 + 0.3), (last_y - last_h, 0.9))


# ---------------------------------------------------------------------------
# Gambar II.3 — Perbandingan blok Transformer / Conformer / + spatial
# (versi Bab II: tanpa catatan hiperparameter Bab III)
# ---------------------------------------------------------------------------
def fig_transformer_variants():
    fig, ax = plt.subplots(figsize=(8.2, 6.8))
    W = 3.5
    gap = 0.5
    MHSA = "@i@Multi-Head\n@i@Self-Attention"
    FF = "@i@Feed-Forward"
    FFh = "@i@Feed-Forward\n@i@(1/2)"
    cols = {
        "Transformer": (-4.0, [
            (MHSA, BLUE_F, BLUE_E),
            ("@i@Add & Norm", GRY_F, GRY_E),
            (FF, BLUE_F, BLUE_E),
            ("@i@Add & Norm", GRY_F, GRY_E),
        ]),
        "Conformer": (0.0, [
            (FFh, BLUE_F, BLUE_E),
            (MHSA, BLUE_F, BLUE_E),
            ("@i@Convolution\n@i@Module", YEL_F, YEL_E),
            (FFh, BLUE_F, BLUE_E),
            ("@i@LayerNorm", GRY_F, GRY_E),
        ]),
        "Conformer +\nSpatial Attention": (4.0, [
            ("@i@Spatial Attention\n(antarelektroda)", RED_F, RED_E),
            (FFh, BLUE_F, BLUE_E),
            (MHSA, BLUE_F, BLUE_E),
            ("@i@Convolution\n@i@Module", YEL_F, YEL_E),
            (FFh, BLUE_F, BLUE_E),
            ("@i@LayerNorm", GRY_F, GRY_E),
        ]),
    }
    top = 0.0
    bottoms = []
    for title, (cx, steps) in cols.items():
        ax.text(cx, top + 1.4, title, ha="center", va="center",
                fontsize=TITLE, fontweight="bold")
        y = top
        ys = []
        for txt, fc, ec in steps:
            h = bh(txt, base=0.95)
            box(ax, cx, y - h / 2, W, h, txt, fc=fc, ec=ec, fs=SUB)
            ys.append((y - h / 2, h))
            y -= h + gap
        for i in range(len(steps) - 1):
            (cy0, h0), (cy1, h1) = ys[i], ys[i + 1]
            arrow(ax, (cx, cy0 - h0 / 2), (cx, cy1 + h1 / 2))
        bottoms.append(ys[-1][0] - ys[-1][1])
    yb = min(bottoms) - 0.4
    finish(fig, ax, "fig_transformer_variants.png",
           (-6.0, 6.0), (yb - 0.4, top + 2.1))


if __name__ == "__main__":
    fig_dataset()
    fig_ecog_pipeline()
    fig_transformer_variants()
    print("done")
